server:
  port: 7406
spring:
  application:
    name: FinBot-Plus
  datasource:
    url: jdbc:sqlite:/Users/wanglongjun/Downloads/record.db
  ai:
    deepseek:
      base-url: https://api.deepseek.com
    openai:
      chat:
        options:
          model: deepseek-chat
    anthropic:
      chat:
        options:
          model: claude-3-7-sonnet-20250219
      base-url: https://api.gptsapi.net
    gemini:
      base-url: https://openrouter.ai/api
      model: google/gemini-2.5-flash-preview
    mcp:
      client:
        stdio:
          connections:
            sqliteMcp:
              command: uv
              args:
                - --directory
                - /Users/wanglongjun/Downloads/servers-2025.4.6/src/sqlite
                - run
                - mcp-server-sqlite
                - --db-path
                - /Users/wanglongjun/Downloads/record.db
        toolcallback:
          enabled=true:

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

telegram:
  userId:
  local:
  token: